# tests/tests.pro
# Separate qmake project for the unit tests.
# Initial pass generated by Raptor Mini (with a lot of help)

TEMPLATE = app
TARGET = ttt_tests        # name of the test executable
CONFIG += console         # don't pull in Qt widgets by default
CONFIG += c++11           # match the main project

INCLUDEPATH += $$PWD/../include

CATCHDIR = /Users/heather/Documents/Personal/Code/Code/Tools/Catch2/lib
INCLUDEPATH += $$CATCHDIR/include

LIBS += $$CATCHDIR/lib/libCatch2Main.a $$CATCHDIR/lib/libCatch2.a

SOURCES += \
    all.cpp \
    test_timeWrapper.cpp
