# tests/tests.pro
# Separate qmake project for the unit tests.
# Initial pass generated by Raptor Mini (with a lot of help)

TEMPLATE = app
TARGET = ttt_tests        # name of the test executable
CONFIG += console         # don't pull in Qt widgets by default
CONFIG += c++11           # match the main project
QT += widgets # Need signal/slot even here 

QMAKE_CXXFLAGS += -g -fprofile-instr-generate -fcoverage-mapping -Wall
QMAKE_LFLAGS += -g -fprofile-instr-generate -fcoverage-mapping

INCLUDEPATH += $$PWD/../include

MOC_DIR = ./moc
OBJECTS_DIR = ./obj

CATCHDIR = /Users/heather/Documents/Personal/Code/Code/Tools/Catch2/lib
INCLUDEPATH += $$CATCHDIR/include

LIBS += $$CATCHDIR/lib/libCatch2Main.a $$CATCHDIR/lib/libCatch2.a
LIBS += -lsqlite3

SOURCES += \
    all.cpp \
    test_timeWrapper.cpp \
    test_timestampProcessor.cpp \
    test_supportCode.cpp \
    test_idGenerators.cpp \
    test_project.cpp \
    test_appClock.cpp \
    test_databaseStore.cpp \
    test_projectManager.cpp \
    test_dataObjects.cpp \
    test_dataInterface.cpp \
    test_TrackerData.cpp

HEADERS += ../include/dataObjects.h \
           ../include/idGenerators.h \
           ../include/project.h \
           ../include/projectbutton.h \
           ../include/projectManager.h \
           ../include/TrackerData.h \
           ../include/dataInterface.h \
           ../include/timeWrapper.h \
           ../include/timestampProcessor.h \
           ../include/appClock.h \
           QTSignalHelper.h

